import utils,codecs, struct,hashlib
# print("abcdef",type("abcdef"))
# print(                            "abcdef".encode("utf-8"),   type("abcdef".encode("utf-8")))
# print(              codecs.decode("abcdef".encode("utf-8"), "hex"), )
# print(codecs.encode(codecs.decode("abcdef".encode("utf-8"), "hex"), "hex"))
# print(codecs.encode(codecs.decode("abcdef".encode("utf-8"), "hex"), "hex").decode())
# print(              codecs.decode("abcdef".encode("utf-8"), "hex") )
# print(              str(codecs.decode("abcdef".encode("utf-8"), "hex") )[1:] )
# print(              str(codecs.decode("abcdef".encode("utf-8"), "hex") ) )
# 
# print(utils.base58CheckEncode(42, 'abc'))
# print(utils.base58CheckDecode(utils.base58CheckEncode(42, 'abc')))
print(utils.base58CheckEncode( 0, '\0\0abc'))
#print(utils.base58CheckDecode(utils.base58CheckEncode(0, '\0\0abc')))
s = utils.base256encode(0x0C28FCA386C7A227600B2FE50B7CAE11EC86D3BF1FBE471BE89827E19D72AA1D)
print(s.encode())
print(type(s))
b = utils.base58CheckEncode(0x80, s)
print(b)
